//
//  MainViewModel.swift
//  StarterKit
//
//  Created by Dmitry Eryshov on 31.05.2024.
//

import Foundation
import kameleoonClient
import os
import SwiftUI

class SDKViewModel: ObservableObject {
    
    private struct Const {
        static let siteCode = "yourSiteCode" // You should change it to your own siteCode.
        static let refreshInterval = 15 // SDK configuration refresh interval.
        static let timeoutInit = 2000 // Timeout for initialization.
    }
    
    private static let logger = Logger(
        subsystem: Bundle.main.bundleIdentifier!,
        category: String(describing: SDKViewModel.self)
    )
            
    private var kameleoonClient: KameleoonClient!
    
    @Published var status: Bool = false
    @Published var initialization: Bool = true
    @Published var result: Result<String, Error>? = nil
    @Published var success: Bool = false
    @Published var params: Params! {
        didSet {
            params.save()
        }
    }

    
    init() {
        initKameleoonClient()
        params = Params()
    }
    
    // Initialize Kameleoon SDK
    private func initKameleoonClient() {
        do {
            // If no visitor is code provided, one will be generated by the SDK itself and will be used for 
            // all future requests. Usually, you should set visitor code as a real user ID.
            let visitorCode: String? = nil
            // KameleoonClientConfig is used to set KameleoonClient settings.
            let config = KameleoonClientConfig(refreshIntervalMinute: Const.refreshInterval)
            // For all SDK activities, you should use the KameleoonClient instance.
            // You should handle the errors properly.
            kameleoonClient = try KameleoonClientFactory.create(
                siteCode: Const.siteCode,
                visitorCode: visitorCode,
                config: config
            )
            SDKViewModel.logger.info("SDK is initializing...")
            // The runWhenReady method will be called after the SDK initialization process is complete.
            // If the SDK is already initialized, the method immediately calls the callback.
            kameleoonClient.runWhenReady(timeoutMilliseconds: Const.timeoutInit) { [weak self] ready in
                guard let self else { return }
                // Either the kameleoonClient is ready, or could not be initialized within the default timeout.
                self.status = ready
                self.initialization = false
                SDKViewModel.logger.info("SDK is \(ready ? "ready" : "not ready") to use")
            }
        } catch KameleoonError.siteCodeIsEmpty {
            // If the provided siteCode is empty.
            SDKViewModel.logger.error("Sitecode is empty")
        } catch KameleoonError.visitorCodeInvalid(let visitorCode) {
            // If the provided visitorCode is not valid
            SDKViewModel.logger.error("Visitor code '\(visitorCode)' is not valid")
        } catch {
            // Base error - normally, this should not happen. You can ignore all of the errors above and 
            // catch only the base error. If you're not interested in specific reason of error.
            SDKViewModel.logger.error("Unexpected Error: \(error.localizedDescription)")
        }
    }
    
    // Get variation
    func getVariation() {
        do {
            let variationKey = try kameleoonClient.getFeatureVariationKey(featureKey: params.featureKey)
            result = Result.success(variationKey)
        } catch KameleoonError.sdkNotReady {
            // The SDK isn't ready yet.
            result = Result.failure(KameleoonError.sdkNotReady)
        } catch KameleoonError.Feature.notFound(let featureKey) {
            // The SDK configuration doesn't contain a feature key.
            result = Result.failure(KameleoonError.Feature.notFound(featureKey))
        } catch KameleoonError.Feature.environmentDisabled(let featureKey, let env) {
            // Feature key is disabled for certain environments.
            result = Result.failure(KameleoonError.Feature.environmentDisabled(featureKey, env))
        } catch {
            // Base error - normally, this should not happen. You can ignore all of the errors above and
            // catch only the base error. If you're not interested in specific reason of error.
            result = Result.failure(error)
        }
        
        switch result {
            case .failure(let failure):
                SDKViewModel.logger.error("\(failure.localizedDescription)")
            default:
                break
        }
    }
}
